 <table  cellspacing="0" cellpadding="0" border="0"><tr><td><table cellspacing="0" cellpadding="0" border="0"><tr><td style="border-right: 2px solid rgb(90, 99, 119); padding-right: 10px; padding-top: 10px; padding-bottom: 10px;"><img src="<?php echo COMPANYLOGO ?>"></td> <td style="padding-left: 10px; padding-top: 10px; padding-bottom: 10px;"><table cellspacing="0" cellpadding="0" border="0">

<tr><td style="padding-bottom: 5px; line-height: 0.7em; text-align: left;"><span style="font-weight: bold; font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(51, 51, 51);">Thanks & Regards,</span> <!----> <!----></td></tr> <!----> 
<tr><td style="padding-bottom: 5px; line-height: 0.7em; text-align: left;"><span style="font-weight: bold; font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(51, 51, 51);"><?php echo ucwords($user_profile_info['firstname']) ?> <?php echo ucwords($user_profile_info['lastname']) ?> </span> <!----> <!----></td></tr> <!----> 
<tr><td style="padding-bottom: 5px; line-height: 0.7em; text-align: left;"><span style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(51, 51, 51);"><?php echo ucwords($user_profile_info['designation']) ?> - <?php echo ucwords($user_profile_info['department']) ?></span> <!----> <!----></td></tr> <!----> 
<tr><td style="padding-bottom: 5px; line-height: 0.7em; text-align: left;"><span style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(51, 51, 51);"></span> <!----> <!----></td></tr> <!----> 
<tr><td style="padding-bottom: 5px; line-height: 0.7em; text-align: left;"><span style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(51, 51, 51);">(ISO 27001:2013 Certified Company)</span> <!----> <!----></td></tr> <!----> 



<tr><td style="padding-bottom: 10px; line-height: 0.7em; text-align: left;"><span style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(51, 51, 51);">E:</span> <a href="mailto:<?php echo $this->user_info['email']; ?>" style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(0, 102, 204);"><?php echo $this->user_info['email']; ?></a> <span style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(90, 99, 119);">|</span> <span style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(51, 51, 51);">W:</span> <a href="https://" style="font-family: Verdana, Geneva, sans-serif; font-size: 0.7em; color: rgb(0, 102, 204);"></a></td></tr> <tr><td style="line-height: 0.7em; text-align: left;"><!----> <span style="font-family: Verdana, Geneva, sans-serif; font-size: 0.56em; color: rgb(51, 51, 51);">.</span></td></tr> <tr><td style="padding-top: 10px; padding-bottom: 5px; text-align: left;"><img src=""></td></tr> <tr><td style="font-family: Verdana, Geneva, sans-serif; font-size: 0.49em; color: rgb(136, 136, 136); max-width: 468px; text-align: justify;">The company accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.</td></tr></table> <p style="font-family: Verdana, Geneva, sans-serif; font-size: 0.49em; color: rgb(136, 136, 136); margin-top: 6px; margin-bottom: 6px;">